### PR TITLE
Add icons for Julia, R, and Stata.

### PR DESCRIPTION
**Pull request by vikjam**
Adds icons for Julia, R and Stata as discussed in Issue #105.

c39d6d36-266b-11e5-9378-f3dcc1b05406

### CODE REVIEW

**Comment by jackolney** [comment]
Can this be merged?

**Comment by egeerardyn** [comment]
I would also like to see this merged.

**Comment by ZacCranko** [comment]
Any developments on this?

**Comment by jackolney** [comment]
Can this be merged any time soon? – this update is starting to drag.

**Comment by ZacCranko** [comment]
I think this repo might be abandoned

**Comment by jackolney** [comment]
Pity – I haven't found a better theme for ST. I might switch to @vikjam 's fork for the time being then.

**Comment by egeerardyn** [comment]
I also think it's a pity that it takes so long to pull in such small PRs. 

Anyhow, it might be more worthwhile to fork this theme and build an improved one, rather than waiting for these PRs to get picked up by @YabataDesign .

**Comment by vikjam** [comment]
I merged @egeerardyn's pull request #113 to the fork I have. I'd be happy to add any of you as contributors to maintain an updated fork until @YabataDesign returns to merge it.

**Comment by ericbbbl** [comment]
Gotcha man. I'll be tracking your ass and haunting you when you least expect it. Pythone.... Out🌹

**Pull request merged**
