### PR TITLE
Sidebar folder and files align fix

### PR DESCRIPTION
**Pull request by indri-indri**
The folders and files in the sidebar should now be aligned.

Fixes Issue #82 and #79

### CODE REVIEW

**Comment by indri-indri** [comment]
Looks like this:
screen shot 2015-04-23 at 23 06 54

**Comment by YabataDesign** [comment]
@indri-indri Thanks so much! Awesome pull requests!

**Comment by dgmstuart** [comment]
This seems to have removed the + and - symbols on folders - see #85 
Is this because the "sidebar folder closed" and "sidebar folder open" sections have been removed?

Perhaps this is only happening for users who (like me) can't see any icons at all (?) - as per #71

**Comment by TheFox** [comment]
Why can't some users (like me) see any icons at all?

**Comment by indri-indri** [comment]
@TheFox 
Sublime Text 2 does not support the icons yet. Updating to Sublime Text 3 would fix this.

@dgmstuart 
Please read my comment in #85 for more information.

**Comment by dgmstuart** [comment]
@indri-indri thanks :)

**Pull request merged**
